name: CI
on: pull_request

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install poetry
        run: |
          python -m pip install -U pip
          python -m pip install poetry==1.6.1

      - name: Run black via poetry
        run: poetry run black **/src/*.py

      - name: Run poetry build
        run: poetry build
